language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.m2/repository"
script:
  - mvn clean package -DskipTests=true

after_success:
  - sudo apt-get install -y sshpass
  - cd ./target
  - sshpass -p $SSH_PASS scp lab.war  $SSH_USER@$SSH_IP:/usr/local/tomcat/webapps
# branches:
#   only:
#     - master
